ExpenseTracker.WebAPI/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ExpenseTracker.WebAPI.Areas.HelpPage.ModelDescriptions;
using ExpenseTracker.WebAPI.Areas.HelpPage.Models;

namespace ExpenseTracker.WebAPI.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

ExpenseTracker.WebAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, width=device-width">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")

    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/nprogress.css" rel="stylesheet" />
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="~/Content/ui-bootstrap-csp.css" rel="stylesheet" />
    <link href="~/Scripts/angular-bootstrap-datetimepicker/css/datetimepicker.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="expenseTracker">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Expense Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#!/home">Home</a></li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li ng-if="authenticated"><a href="#!/users">Users</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li ng-if="!authenticated"><a href="#!/signup">Sign up</a></li>
                    <li ng-if="!authenticated"><a href="#!/signin">Sign in</a></li>
                    <li ng-if="authenticated"><a href="#" ng-click="signOut()">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/angular-ui-router.js"></script>
    <script src="~/Scripts/angular-local-storage.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/nprogress.js"></script>

    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/angular-bootstrap-datetimepicker/js/datetimepicker.js"></script>
    <script src="~/Scripts/angular-bootstrap-datetimepicker/js/datetimepicker.templates.js"></script>
    
    <script src="~/app/dist/scripts.js"></script>
</body>
</html>